### ISSUE TITLE
Bug on import vue-axios-plugn

### ISSUE THREAD

**Issue by davidcostadev** [yugasun/vue-axios-plugin#1]
iam try to use package and show this error

> ERROR in ./~/vue-axios-plugin/index.js
> Module parse failed: /path/project/node_modules/vue-axios-plugin/index.js Unexpected token (59:8)
> You may need an appropriate loader to handle this file type.
> |     get: (url, data, options) => {
> |       let axiosOpt = {
> |         ...defaultConfig,
> |         ...options,
> |         ...{
>  @ ./src/plugins/vue-axios-plugin.js 2:0-46
>  @ ./src/main.js
>  @ multi ./build/dev-client ./src/main.js
> 

~plugin/vue-axios.plugin.js

```
import Vue from 'vue'
import VueAxiosPlugin from 'vue-axios-plugin'

Vue.use(VueAxiosPlugin)
```

**Comment by yugasun** [comment]
@davidcostadev this plugin is wrote by ES6，so you need use babel, please update your webpack, like below:

```
// resolve is the function to join your folder path
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

{
  test: /\.js$/,
  loader: 'babel-loader',
  include: [resolve('src'), resolve('test'), resolve('node_modules/vue-axios-plugin')]
},
```

you can find the config in [README](https://github.com/yugasun/vue-axios-plugin/blob/master/README.md)
